version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: ./scripts/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/application_start.sh
      timeout: 300
      runas: root
